[package]
name = "billing"
version = "1.0.0"
authors = ["OpenAPI Generator team and contributors"]
description = "SaaSus Billing API Schema"
# Override this license by providing a License Object in the OpenAPI.
license = "Unlicense"
edition = "2018"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "^2.2"
uuid = { version = "^1.0", features = ["serde", "v4"] }
hyper = { version = "~0.14", features = ["full"] }
hyper-tls = "~0.5"
http = "~0.2"
base64 = "~0.7.0"
futures = "^0.3"
hmac = "0.12.1"
sha2 = "0.10.8"
chrono = "0.4.31"
